included:
  #- ../NmeaParser
  - ../../NmeaParser/Classes
excluded:
  - Pods
  - Nimble
  - Quick

disabled_rules: # rule identifiers to exclude from running
#  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  NmeaParser
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Johannes Steudle\. All rights reserved\.
                    \/\/

force_cast: warning
line_length: 120
number_separator:
  minimum_length: 5
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
