platform :ios, '12.0'
use_frameworks!

target 'NmeaParser_Example' do
  pod 'NmeaParser', :path => '../'

  target 'NmeaParser_Tests' do
    inherit! :search_paths

    pod 'Quick' #, '~> 1.0.0'
    pod 'Nimble' #, '~> 5.1.1'
  end
end
